### ISSUE TITLE
Error: Error getting missing player or bypassing age-restriction: This video is unavailable

### ISSUE THREAD

**Issue by ksawerek** [user234683/youtube-local#169] opened 2023-04-30 06:37 UTC
Used to work after refreshing a few times

**Comment by hDmtP** [comment] 2023-04-30 21:51
> Used to work after refreshing a few times

Well now the videos aren't loading anymore.

Btw I'm using this one : https://git.sr.ht/~heckyel/yt-local

**Comment by user234683** [comment] 2023-05-01 03:34
Duplicate of #165 
However, the fix for that issue has its own major issue, being discussed in #168

**Comment by user234683** [comment] 2023-05-02 04:28
All fixed in latest release

**Closed by user234683** 2023-05-02 04:28 UTC
Labels: duplicate
